### ISSUE TITLE
Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by sandrods** [thiagoarrais/rodf#12]
I'm getting this error
```
Encoding::UndefinedConversionError
"\xE0" from ASCII-8BIT to UTF-8
```

after updating to version 0.3.6.

I'm assuming it's caused by this set_ecoding
https://github.com/thiagoarrais/rodf/blob/master/lib/odf/document.rb#L53

Any reason you set the encoding this way?

Regards, 

Sandro

**Comment by thiagoarrais** [comment]
I've reviewed the commit that introduced that line, but I can't see any specific reason why that encoding is used. But I also am not able to reproduce this bug.

Questions:

1. Can you provide a small code sample that exposes the bug?
2. Have you tried removing that line and running your code without it?

**Comment by sandrods** [comment]
Sorry Thiago, 

It's been so long I don't remember where it was happening. 
Thanks for your effort

**Comment by thiagoarrais** [comment]
Sorry to hear that. I'll try to be faster next time. :-)

Anyway... Feel free to reopen this issue if you stumble upon it again.

**Comment by schmidt** [comment]
I am running into this error, when generating odt files within a rails app. It looks, like the `Encoding.default_internal` causes things to break.

The following code represents a minimal example, that breaks on my machine (ruby-2.2.4 on OS X).

```ruby
require 'odf/text'

Encoding.default_internal = "UTF-8"

ODF::Text.file("test.odt") {}
```

I get the following stack trace:

```
.../gems/rodf-0.3.6/lib/odf/document.rb:36:in `write': "\x86" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from .../gems/rodf-0.3.6/lib/odf/document.rb:36:in `<<'
	from .../gems/rodf-0.3.6/lib/odf/document.rb:36:in `block in write_to'
	from .../gems/rodf-0.3.6/lib/odf/document.rb:36:in `open'
	from .../gems/rodf-0.3.6/lib/odf/document.rb:36:in `write_to'
	from .../gems/rodf-0.3.6/lib/odf/document.rb:32:in `file'
	from test.rb:5:in `<main>'
```

When removing the `Encoding..` line in the example, the script works as expected. Unfortunately, I cannot do much about the default internal encoding used within the rails app. I assume, it would be possible to change it, but I guess other things would start to break.

**Comment by schmidt** [comment]
After some more fiddling, I found a viable solution and added a basic test. I've just added a pull request at #16.
