### ISSUE TITLE
Explanation for styles per property type

### ISSUE THREAD

**Issue by westonganger** [thiagoarrais/rodf#14]
I am finding it very difficult to style using this gem mainly due to lack of the documentation around the styling. So far I have managed to apply a bold style to a cell.
1. How to set a cell/columns width? (and maybe how to get the cell /column to autosize?)
2. How to set a row background color?

**Comment by thiagoarrais** [comment]
This is a really low level library, prior knowledge of the ODF spec _is_ required. I know: that sucks...

What I would do in your case would be to experiment creating and depackaging some ODF files created with Libre Office (or wherever else)... Again: that sucks really bad...

And maybe write a higher level library on top of rODF? Or maybe increment it with a nicer API?

**Comment by thiagoarrais** [comment]
I guess you already solved that row background color problem, right? As given by [this PR](https://github.com/thiagoarrais/rodf/pull/15) you opened.

**Comment by thiagoarrais** [comment]
For column width, here's a "hello world" example:

    require 'odf/spreadsheet'

    ODF::Spreadsheet.file("/tmp/my-spreadsheet.ods") do
      style 'wide-column', :family => :column do
        property :column, 'column-width' => "8.0cm"
      end
      table 'Wide column' do
        column :style => 'wide-column'
        row { cell 'Wiiiiide' }
      end
    end

But then again... Auto-sizing would involve some mining in the spec. Sucks!

**Comment by westonganger** [comment]
I am currently in the process of creating the documentation for more styles from the source code of a PHP libarary: https://github.com/box/spout/blob/584121d47887bdfe063c4dfdee24d490e40466d2/src/Spout/Writer/ODS/Helper/StyleHelper.php

**Comment by westonganger** [comment]
All of the styles I could figure out from the above link have been documented in the README.md for v1.0.0
