### ISSUE TITLE
Support more types

### ISSUE THREAD

**Issue by westonganger** [thiagoarrais/rodf#17]
When trying to add a float value it does not show.

I think the cause is on line 75 of `lib/odf/cell.rb` you basically only allow :string

Valid `office:value-types` are as follows :float, :percentage, :currency, :date, :time which you can read about here: http://books.evc-cit.info/odbook/ch05.html#table-value-table

I would be interested in helping maintain this gem such as accepting PR's, adding features like this one, and releasing new versions if your willing to give me the permissions.

**Comment by thiagoarrais** [comment]
That would be excellent, @westonganger. We can even make your fork the canonical one, change the gem's homepage, etc., if you'd like.

How can we do that without making it (too) confusing for people?

**Comment by westonganger** [comment]
I think the code should stay here in this repo. In my experience things can get confusing when moving repo's around, plus you have done tons of work here which you should get credit for.

I just want the ability to help get new features through, accept PR's, add documentation, and release new versions. If you are interested in this, you should be able to add people as Collaborators under the Settings tab of this repo.

**Comment by thiagoarrais** [comment]
Done. I've also added [westonganger](https://rubygems.org/profiles/westonganger) as gem owner in rubygems. You should be able to `gem push` now. Let me know if that isn't you.

**Comment by westonganger** [comment]
v1.0.0 automatically determines the correct type based on the value passed to cell if one wasnt specified
