### ISSUE TITLE
Number Styles

### ISSUE THREAD

**Issue by mauriciomenegaz** [thiagoarrais/rodf#20]
Hi

I am trying to create a number style for integers with thousands separator. I created a spreadsheet in LibreOffice Calc to see the generated xml for the style I want, and I got this:

```xml
<number:number-style style:name="N3">
  <number:number number:decimal-places="0" number:min-integer-digits="1" number:grouping="true"/>
</number:number-style>
```

Now I am trying to make this style in RODF. I tried it this way:

```ruby
data_style 'number-with-delimiter', 'number' do
  number 'decimal-places' => '0'
end
```

And I get this output:

```xml
<number:number-style style:name="number-with-delimiter">
  <number:number number:style="" number:textual=""/>
</number:number-style>
```

Seems that the problem is that one method in `style_section.rb` is allowing just two attributes for the tag, which are not the ones I need:

https://github.com/thiagoarrais/rodf/blob/0e58be76e0b85aa6fb9a2d6fe5470bca99995348/lib/rodf/style_section.rb#L35-L37

Is my diagnostic correct? Would you be willing to accept a pull request to allow more attributes in the referred method?

**Comment by westonganger** [comment]
I believe your diagnosis is correct. Yeah I would accept a PR if you get it working. Try to add some tests too please.

**Comment by westonganger** [comment]
PR #21 merged. Closing.
