### ISSUE TITLE
Line break in cell

### ISSUE THREAD

**Issue by privatus** [thiagoarrais/rodf#22]
When I add value "text\nnew line" to cell I get "\<text:p\>text\nnew line</text:p>" in content.xml. It should be rather "\<text:p\>text</text:p>\<text:p\>new line</text:p>". 

Thx 4 Your work on rodf.

**Comment by tenpaiyomi** [comment]
I'll tackle this one.

**Comment by tenpaiyomi** [comment]
Here you go, @privatus.  @thiagoarrais, let me know if this is acceptable.  I included tests to cover the new behavior as well.

**Comment by privatus** [comment]
Line breaks work great with this correction :)
Thx!
